SESAME_TAR=sesamesim-1.5.1.tar.gz
MAPPINGMODULE_TAR=mappingmodule.tgz
BASE_URL=http://pc-vlab09.science.uva.nl/files/

# TODO needs to be a parameter. (check parameters)
INSTALLDIR=/home/spolstra/opt2 

# Will contain export to set sesame environment
SESAME_ENV_FILE=sesame.env

# Takes two parameters. The response from a command and error message
# If the response is not zero, print the error message and exit
check() {
    if [ $1 -ne 0 ]
    then
        echo -e "\e[1;31mERROR: $2\e[0m"
        exit 1
    fi
}

# This function downloads the flow components. Requires Internet access
get_and_unpack_packages() {

    echo "wget -q -nc $BASE_URL/$SESAME_TAR"
    wget -q -nc $BASE_URL/$SESAME_TAR
    check $? "Cannot download $SESAME_TAR file"
    tar xzf $SESAME_TAR

    echo "wget -q -nc $BASE_URL/$MAPPINGMODULE_TAR"
    wget -q -nc $BASE_URL/$MAPPINGMODULE_TAR
    check $? "Cannot download $MAPPINGMODULE_TAR file"
    tar xzf $MAPPINGMODULE_TAR
}

# Runs setup of mappingmodule
# SESAME_ENV_FILE is appended with PYTHONPATH definition
setup_mappingmodule() {
    cd `basename $MAPPINGMODULE_TAR .tgz`
    python setup.py install --prefix $INSTALLDIR --record installed-files.txt
    
    # extract install directory from installed-files.txt
    location=`sed  s/site-packages.*// installed-files.txt | head -1`
    # Append export to SESAME_ENV_FILE
    echo "export PYTHONPATH+=:$location" >> ../$SESAME_ENV_FILE
    # Also needed for installation
    export PYTHONPATH+=:$location
    cd ..
}

# Sesame setup
setup_sesame() {
    # Enter Sesame root
    cd `basename sesamesim-1.5.1.tar.gz .tar.gz`

    # Add environment to env file.
    echo "export \$PATH=$INSTALLDIR/bin:\$PATH" >> ../$SESAME_ENV_FILE
    # Also needed during installation.
    export $PATH=$INSTALLDIR/bin:$PATH
    
    ./configure --prefix=$INSTALLDIR
    # TODO check succes
    make
    make install

    # Now find the location where the sesame python code is installed
    # TODO this could be the same location now? is that also the case?
    location=`ls -d $INSTALLDIR/lib*/python*/site-packages`
    # ..and append it to SESAME_ENV_FILE
    echo "export PYTHONPATH+=:$location" >> ../$SESAME_ENV_FILE
    # Also needed for make check
    export PYTHONPATH+=:$location

    # Run checks
    # make check
    cd ..
}

#---------------------------------------------------------------------- 
# Start of Main 
#---------------------------------------------------------------------- 

# Download packages and unpack
get_and_unpack_packages

# SESAME_ENV_FILE will contain the exports that setup the sesame environment
echo "# Environment setup file generated by $0" > $SESAME_ENV_FILE

setup_mappingmodule
setup_sesame

# source sesame.env (why eval $(..) no work?)
